# Generated by Django 4.2.26 on 2025-11-25 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/gallery/'),
            preserve_default=False,
        ),
    ]
