# Generated by Django 4.2.26 on 2025-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_userprofile_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='items_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/logos/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
