# Generated by Django 4.2.26 on 2025-12-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_status_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/images/'),
        ),
    ]
