# Generated by Django 4.2.26 on 2025-12-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sellerprofile_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='If set, this category belongs only to this seller/shop.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('seller', 'name'), name='unique_category_name_per_seller'),
        ),
    ]
